// kitchen_sink.h — GEM+goto+PEC, 2 focusers, rotator, weather, all 8 feature types.
#define HOST_NAME "OnStepKitchenSink"
#define MOUNT_TYPE GEM
#define AXIS1_DRIVER_MODEL TMC2209
#define AXIS1_STEPS_PER_DEGREE 12800
#define AXIS1_LIMIT_MIN -220
#define AXIS1_LIMIT_MAX 220
#define AXIS1_SENSE_HOME LOW
#define AXIS1_SENSE_LIMIT_MIN LIMIT_SENSE
#define AXIS1_SENSE_LIMIT_MAX LIMIT_SENSE
#define AXIS2_DRIVER_MODEL TMC2209
#define AXIS2_STEPS_PER_DEGREE 12800
#define AXIS2_LIMIT_MIN -90
#define AXIS2_LIMIT_MAX 90
#define AXIS2_SENSE_HOME OFF
#define AXIS2_SENSE_LIMIT_MIN LIMIT_SENSE
#define AXIS2_SENSE_LIMIT_MAX LIMIT_SENSE
#define GOTO_FEATURE ON
#define SLEW_RATE_BASE_DESIRED 3.0
#define PEC_STEPS_PER_WORM_ROTATION 12800
#define AXIS3_DRIVER_MODEL TMC2209
#define AXIS3_STEPS_PER_DEGREE 64
#define AXIS3_LIMIT_MIN 0
#define AXIS3_LIMIT_MAX 360
#define AXIS4_DRIVER_MODEL TMC2209
#define AXIS4_STEPS_PER_MICRON 0.5
#define AXIS4_LIMIT_MIN 0
#define AXIS4_LIMIT_MAX 50
#define AXIS5_DRIVER_MODEL TMC2209
#define AXIS5_STEPS_PER_MICRON 0.5
#define AXIS5_LIMIT_MIN 0
#define AXIS5_LIMIT_MAX 50
#define WEATHER BME280_0x76
#define STATUS_BUZZER_DEFAULT ON
#define FEATURE1_PURPOSE SWITCH
#define FEATURE1_NAME "SWITCH 1"
#define FEATURE2_PURPOSE ANALOG_OUTPUT
#define FEATURE2_NAME "ANALOG OUT"
#define FEATURE3_PURPOSE DEW_HEATER
#define FEATURE3_NAME "DEW HEATER"
#define FEATURE4_PURPOSE INTERVALOMETER
#define FEATURE4_NAME "INTERVALOMTR"
#define FEATURE5_PURPOSE MOMENTARY_SWITCH
#define FEATURE5_NAME "MOMENTARY"
#define FEATURE6_PURPOSE HIDDEN_SWITCH
#define FEATURE6_NAME "HIDDEN"
#define FEATURE7_PURPOSE COVER_SWITCH
#define FEATURE7_NAME "COVER"
#define FEATURE8_PURPOSE SWITCH
#define FEATURE8_NAME "SWITCH 8"
